#!/bin/bash

set -eo pipefail

. "$(dirname "$0")"/common

data=$(download)

function values() {
  local v found
  if [ -n "$version" ] && versions <<< $data | grep -q "$version"
  then
    found=0
    while read v
    do
      if [ $found = 0 ]
      then
        [ "$v" = "$version" ] || continue
        found=1
      fi

      echo $v
    done < <(versions <<< $data)
  else
    versions <<< $data
  fi
}

values \
| jq -R '{"version": (.) }' \
| jq --slurp \
>&3
