#!/bin/bash

set -eo pipefail

. "$(dirname "$0")"/common

data=$(download)
meta=$(metadata $version <<< $data)

cd "$1"

echo $version > version
echo $board_manager_url > board_manager_url

cat >&3 <<EOT
{
  "version": {
    "version": "$version"
  },
  "metadata": [
$meta
  ]
}
EOT
